# Configuration file for WelcomeMessage
# Author: Kroavex

# =========
# VARIABLES
# =========
# %player% - Player name.

# Messages sent when a player joins the server for the first time.
new-player:

    # Determines whether the message is sent in the form a title
    # true - Title
    # false - Regular message
    haveTitle: true
    
    title-settings:
    
        title: "DEV SERVER"
        
        subtitle: Welcome, {player}!
        
        fadein-time: 30
        
        stay-time: 50
        
        fadeout-time: 20
    
    # Message to send if haveTitle is false.
    message: Welcome to the server, {palyer}!

# Messages sent when a player who has played before joins.
returning-player:
    
    # Determines whether the message is sent in the form a title
    # true - Title
    # false - Regular message
    haveTitle: false
    
    title-settings:
    
        title: "&4DEVELOPMENT"
        
        subtitle: Welcome back, {player}!
        
        fadein-time: 30
        
        stay-time: 50
        
        fadeout-time: 20
    
    # Message to send if haveTitle is false.
    message:
        - '&2&l***DEVELOPMENT SERVER***'
        - '&aWelcome back, %player%.'